### ISSUE TITLE
Windows identifies a malware

### ISSUE THREAD

**Issue by Billy055** [Lindacoin/Linda#10]
Not able to use the wallet..... Windows 10 deletes it.

**Comment by Erebus999** [comment]
News to the Problem?

**Comment by wlalele** [comment]
+1

**Comment by Humanoid1990** [comment]
Same issue here! Windows wallet has a virus inside the file. When will this be fixed?

**Comment by nisanb** [comment]
Fixed on version 2 -> #25 
Please close the ticket.
