### ISSUE TITLE
Hey guys?  Is this project still alive?

### ISSUE THREAD

**Issue by gavinb2c** [Lindacoin/Linda#11]
Hi,

Linda seems to have a growing interest, but there appears to be no development, contact form doesnt work on the website, the slack channel link is dead, and responses to questions on twitter go unanswered.

Could you please provide a statement on the future plans of Linda,  is it an active project?  Is anyone still involved at a technical level?

Thanks.

**Comment by Esqarrouth** [comment]
Looks dead to me

**Comment by bluedragon11** [comment]
Not sure what to think. There is interest in it, obviously. As far as dev??? I'm vested but may pull out due to this issue.

**Comment by focus5studios** [comment]
Meh me think it's dead. Even if they're busy with improving the project, tell tale signs of abandonment are all over the place.

**Comment by edwardlow** [comment]
Probably overtaken by a group of whales, but it might get a pump because of that...

**Comment by nisanb** [comment]
It's not dead.

**Comment by Esqarrouth** [comment]
Why not? Whats going on? What is the roadmap?

**Comment by nisanb** [comment]
www.lindacoin.com

**Comment by Duskfall** [comment]
No commits for 15 days

**Comment by nisanb** [comment]
15 days? Then I guess the project is dead.
