### ISSUE TITLE
Bootstrap?

### ISSUE THREAD

**Issue by SefaMuratcanKatirci** [Lindacoin/Linda#12]
Is there any bootstrap for Linda Wallet? It has started  to sync 20 hours ago and could not reach even the half..

**Comment by CryptoBooger** [comment]
Just wanted to let you know this Drop Box guide contains the Bootstrap. You can verify its authenticity on Linda Coin Discord in the Tips-N-Guides Section. The bootstrap is there for OSX also. https://discordapp.com/channels/395933744751443978/400532495298199554

Windows Guide with Bootstrap. https://www.dropbox.com/s/g64zj9iy7163n3c/Staking%20Tutorial.docx?dl=0

OSX Guide with Bootsrap-https://docs.google.com/document/d/1ZYAt4lWbRi7SqE8NEGkGFM43oG3mqaZWocbA3RxdeXg/edit

**Comment by nisanb** [comment]
Answered by @CryptoBooger. Please close the ticket.
