### ISSUE TITLE
Windows 10 Wallet

### ISSUE THREAD

**Issue by Humanoid1990** [Lindacoin/Linda#13]
The Windows wallet has a virus in the file. When can we expect a new clean wallet for Windows?

**Comment by Gtibroeder** [comment]
I think the project is dead?

**Comment by cksagherian** [comment]
Seriously @Gtibroeder what are you talking about? The project is just coming to life? It's FARE from dead! lol

**Comment by tpenner** [comment]
This is a duplicate of issue #10

**Comment by Gtibroeder** [comment]
@cksagherin show me proof..

**Comment by Typhoonx53** [comment]
@Gtibroeder New website with new team released today and new wallet in beta testing for starters.
DYOR and stop spreading FUD

**Comment by nisanb** [comment]
Duplicate of #10 
Will be fixed at v2 -> #25
