### ISSUE TITLE
Wallet Keeps Crashing

### ISSUE THREAD

**Issue by sicXnull** [Lindacoin/Linda#15]
Can't even sync. Crashes within 10 minutes or so. No errors, just quits.

**Comment by Typhoonx53** [comment]
New wallet will be released shortly, it is currently in testfase (beta)
I suggest you wait a bit longer for the new release if you haven't completed the sync yet.
Kind regards

**Comment by nisanb** [comment]
Will be fixed at wallet version v2 -> #25 
Please close the ticket.
