### ISSUE TITLE
darkweb.cpp masternode.cpp and max orphan blocks when syncing

### ISSUE THREAD

**Issue by ceeray** [Lindacoin/Linda#17]
I had to modify the statement:

bool* pfMissingInputs = false;

to

bool* pfMissingInputs;

on darkweb.cpp line 977
and on masternode.cpp line 160

in order to get it to compile on Ubuntu 17.10
I'm running a headless server

also when I let Linda sync on it's own it seemed like it got stuck on orphan block 751, so I just downloaded the bootstrap and seems to be syncing ok now

**Comment by ceeray** [comment]
incidentally I found the fix for those 2 files in Renoscoin GitHub, seems like they use the same code

https://github.com/RenosCoin/RenosCoin

**Comment by nisanb** [comment]
Will be fixed asap.
