### ISSUE TITLE
Windows wallet trojan

### ISSUE THREAD

**Issue by jv65644** [Lindacoin/Linda#19]
This has been asked before with no reply/solution. This windows wallet on win10 shows the file as being a trojan. Is there a planned fix for this issue?

**Comment by nisanb** [comment]
Yes, it will be fixed.

**Comment by nisanb** [comment]
Will be fixed on version 2 -> #25

**Comment by dhurstell** [comment]
Yes, I found it too.  Please consider removing the downloads until it is fixed.  It is far better than opening the crypto userbase to a security issue, and ending up with everyone's crypto stolen

**Comment by nisanb** [comment]
There is no risk using the wallet.

**Comment by burninmedia** [comment]
Might be no risk but it's really hard to download if it's getting flagged as a trojan.

**Comment by nisanb** [comment]
Will be fixed asap.
