### ISSUE TITLE
a compiled Linux wallet issue

### ISSUE THREAD

**Issue by ceeray** [Lindacoin/Linda#24]
I just got my first stake in a Linux wallet I compiled, listtransactions said 4447 linda reward but the wallet only went up by 1186. I checked the tx on lindachain.com and there were 2 recipients for the 4447. my 1186 and another 3261, so I guess the answer is that block reward got split to to recipients but the wallet is not seeing that. Another guy in discord mentioned the same problem.

**Comment by nisanb** [comment]
Since this is only one transaction, the output is split both ways.
Listtransactions shows the output of all the transaction.

Not an issue, please close the ticket :-).
