### ISSUE TITLE
New Windows Download does not unzip

### ISSUE THREAD

**Issue by ksteigerwald** [Lindacoin/Linda#29]
I am unable to unzip the new windows release. >> 
"Cannot determine compressed stream type."

**Comment by nisanb** [comment]
Please try using Winrar software.

**Comment by ksteigerwald** [comment]
I tried the 32 bit link... sorry I haven't used a Windows machine in close to 10 years. Picked up one just to stake my linda coins ;)

**Comment by nisanb** [comment]
You can use Winrar software in order to extract the latest release.
I will add a ZIP file as well soon.

**Comment by ksteigerwald** [comment]
Awesome, after installing WinRAR, I am able to extract the file. Bringing back memories of the altbinary days. The zip file you mention, will this be a link to a snapshot of the blockchain? If not, where might I get a copy to speed up the sync time?

**Comment by nisanb** [comment]
There is a bootstrap file that was uploaded a few hours ago, on the readme file on our GitHub.

**Comment by ksteigerwald** [comment]
all set, thanks for your help!
