### ISSUE TITLE
Unable to expose Linda RPC

### ISSUE THREAD

**Issue by davidstoneham** [Lindacoin/Linda#31]
When using Linda on windows there is no Lindad file to run the RPC commands on. Similarly running linda-qt -server just opens Linda without starting the server.

**Comment by nisanb** [comment]
The RPC Server is still running in the background.
You can enter its' commands through the help -> debug -> console menu, or use an external programming language to connect to the RPC Server.

**Comment by davidstoneham** [comment]
The PRC server should be available through the cmd in windows like it is in Linux through Lindad
