### ISSUE TITLE
staking problem

### ISSUE THREAD

**Issue by hi0b73** [Lindacoin/Linda#35]
after two days of staking, but not reveiving a stake I wthdraw 50k of my linda to an exchange and after this action the wallet showed I have no ripe coins.. I thought the ripe status and staking-status was  stored per coin.. is this new in the new wallet? I think this is an failure.

**Comment by LindaGoldfish** [comment]
Hello hi0b73, The maturing stage of a coin will occur every time you receive a new stake. It is not advised to do any withdraws during the maturing stage as it will increase the time of maturity. 

Examples
A. If you have 5 hours left on the maturing process, and you withdraw 50k coins, it will have to remature. 
B. After you receive rewards for a stake, the maturing process will reoccur (24 hours) before you can begin staking rewards again.

**Comment by nisanb** [comment]
Thank you goldfish.
