### ISSUE TITLE
Segmentation fault Wallet Version 1.0.1.3-g

### ISSUE THREAD

**Issue by SJablonska** [Lindacoin/Linda#36]
Hi,

System: MX Linux, latest version, updates, etc.

I have the following issue: When running Wallet Version 1.0.1.3-g I get a Segmentation fault.

Result gdb Linda-qt:

(gdb) run
Starting program: /home/mx1-admin/.Linda/Linda-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffedca2700 (LWP 14112)]

Thread 1 "Linda-qt" received signal SIGSEGV, Segmentation fault.
0x0000000000dc2a78 in QXcbWMSupport::updateNetWMAtoms() ()

(Version 1.0.1.1 runs without problems).

**Comment by BraapAround** [comment]
@SJablonska You're on an old version. Join our Discord if you still have problems. You can close this issue.
