### ISSUE TITLE
miniupnpc error

### ISSUE THREAD

**Issue by atze09** [Lindacoin/Linda#48]
Hello guys,
I am trying to build the wallet on RPi3 with Ubuntu Mate.
I get stuck at miniupnpc with the error after make init upnpc-static it get:
make: *** No rule to make target 'init'. Stop.

What is the failure?
can anyone help me out?

**Comment by atze09** [comment]
The second error i get during qt configure is:
`piserver@piserver-desktop:~/deps/qt-everywhere-opensource-src-5.4.2$ ./configure -static -opensource -release -confirm-license -no-compile-examples -nomake tests -prefix ~/deps/Qt/5.4.2_static -qt-zlib -qt-libpng -no-libjpeg -qt-xcb -qt-freetype -qt-pcre -qt-harfbuzz -largefile -no-openssl -gtkstyle -skip wayland -skip qtserialport -skip script -pulseaudio -alsa -c++11 -nomake tools
+ cd qtbase
+ /home/piserver/deps/qt-everywhere-opensource-src-5.4.2/qtbase/configure -top-level -static -opensource -release -confirm-license -no-compile-examples -nomake tests -prefix /home/piserver/deps/Qt/5.4.2_static -qt-zlib -qt-libpng -no-libjpeg -qt-xcb -qt-freetype -qt-pcre -qt-harfbuzz -largefile -no-openssl -gtkstyle -skip wayland -skip qtserialport -skip script -pulseaudio -alsa -c++11 -nomake tools

This is the Qt Open Source Edition.

You are licensed to use this software under the terms of
the Lesser GNU General Public License (LGPL) versions 2.1.
You are also licensed to use this software under the terms of
the GNU Lesser General Public License (LGPL) versions 3.

You have already accepted the terms of the Open Source license.

Creating qmake...
make: Nothing to be done for 'first'.
Running configuration tests...
PulseAudio support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to /home/piserver/deps/qt-everywhere-opensource-src-5.4.2/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /home/piserver/deps/qt-everywhere-opensource-src-5.4.2/qtbase/configure to continue.
piserver@piserver-desktop:~/deps/qt-everywhere-opensource-src-5.4.2$ ./configure -static -opensource -release -confirm-license -no-compile-examples -nomake tests -prefix ~/deps/Qt/5.4.2_static -qt-zlib -qt-libpng -no-libjpeg -qt-xcb -qt-freetype -qt-pcre -qt-harfbuzz -largefile -no-openssl -gtkstyle -skip wayland -skip qtserialport -skip script -pulseaudio -alsa -c++11 -nomake tools -v
+ cd qtbase
+ /home/piserver/deps/qt-everywhere-opensource-src-5.4.2/qtbase/configure -top-level -static -opensource -release -confirm-license -no-compile-examples -nomake tests -prefix /home/piserver/deps/Qt/5.4.2_static -qt-zlib -qt-libpng -no-libjpeg -qt-xcb -qt-freetype -qt-pcre -qt-harfbuzz -largefile -no-openssl -gtkstyle -skip wayland -skip qtserialport -skip script -pulseaudio -alsa -c++11 -nomake tools -v

This is the Qt Open Source Edition.

You are licensed to use this software under the terms of
the Lesser GNU General Public License (LGPL) versions 2.1.
You are also licensed to use this software under the terms of
the GNU Lesser General Public License (LGPL) versions 3.

You have already accepted the terms of the Open Source license.

Precompiled-headers support enabled.
g++ -c -fvisibility=hidden fvisibility.c
Symbol visibility control enabled.
g++ -o libtest.so -shared -Wl,-Bsymbolic-functions -fPIC bsymbolic_functions.c
bsymbolic_functions.c:2:2: error: #error "Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129)."
 #error "Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129)."
  ^
Symbolic function binding disabled.
DEFAULT_INCDIRS="/usr/include/c++/5
/usr/include/arm-linux-gnueabihf/c++/5
/usr/include/c++/5/backward
/usr/lib/gcc/arm-linux-gnueabihf/5/include
/usr/local/include
/usr/lib/gcc/arm-linux-gnueabihf/5/include-fixed
/usr/include/arm-linux-gnueabihf
/usr/include
"
DEFAULT_LIBDIRS="/usr/lib/gcc/arm-linux-gnueabihf/5
/usr/lib/arm-linux-gnueabihf
/usr/lib
/lib/arm-linux-gnueabihf
/lib
"
Creating qmake...
make: Nothing to be done for 'first'.
Running configuration tests...
Found pkg-config from $PATH: /usr/bin/pkg-config
Determining architecture... ()
g++ -c -pipe -g -Wall -W -fPIC  -I. -I../../mkspecs/linux-g++ -o arch.o arch.cpp
g++  -o arch arch.o    
    Found architecture in binary
CFG_ARCH="arm"
CFG_CPUFEATURES=""
System architecture: 'arm'
Host architecture: 'arm'
C++11 auto-detection... ()
g++ -c -pipe -O2 -std=c++0x -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o c++11.o c++11.cpp
g++ -Wl,-O1 -o c++11 c++11.o    
C++11 enabled.
floatmath auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o floatmath.o floatmath.cpp
g++ -Wl,-O1 -o floatmath floatmath.o    
floatmath enabled.
sse2 auto-detection... ()
g++ -c -pipe -msse2 -g -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o sse2.o sse2.cpp
g++: error: unrecognized command line option ‘-msse2’
Makefile:191: recipe for target 'sse2.o' failed
make: *** [sse2.o] Error 1
sse2 disabled.
mtdev auto-detection... ()
Project ERROR: mtdev development package not found
mtdev disabled.
DB2 auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o db2.o db2.cpp
db2.cpp:34:20: fatal error: sqlcli.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'db2.o' failed
make: *** [db2.o] Error 1
DB2 disabled.
InterBase auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o ibase.o ibase.cpp
ibase.cpp:34:19: fatal error: ibase.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'ibase.o' failed
make: *** [ibase.o] Error 1
InterBase disabled.
MySQL (thread-safe) auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o mysql.o ../mysql/mysql.cpp
../mysql/mysql.cpp:34:19: fatal error: mysql.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'mysql.o' failed
make: *** [mysql.o] Error 1
MySQL (thread-safe) disabled.
MySQL (thread-unsafe) auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o mysql.o mysql.cpp
mysql.cpp:34:19: fatal error: mysql.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'mysql.o' failed
make: *** [mysql.o] Error 1
MySQL (thread-unsafe) disabled.
OCI auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o oci.o oci.cpp
oci.cpp:34:17: fatal error: oci.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'oci.o' failed
make: *** [oci.o] Error 1
OCI disabled.
ODBC auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o odbc.o odbc.cpp
odbc.cpp:37:17: fatal error: sql.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'odbc.o' failed
make: *** [odbc.o] Error 1
ODBC disabled.
iODBC auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o iodbc.o iodbc.cpp
iodbc.cpp:34:17: fatal error: sql.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'iodbc.o' failed
make: *** [iodbc.o] Error 1
iODBC disabled.
PostgreSQL auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o psql.o psql.cpp
psql.cpp:34:22: fatal error: libpq-fe.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'psql.o' failed
make: *** [psql.o] Error 1
PostgreSQL disabled.
SQLite2 auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o sqlite2.o sqlite2.cpp
sqlite2.cpp:34:20: fatal error: sqlite.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'sqlite2.o' failed
make: *** [sqlite2.o] Error 1
SQLite2 disabled.
TDS auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o tds.o tds.cpp
tds.cpp:34:22: fatal error: sybfront.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'tds.o' failed
make: *** [tds.o] Error 1
TDS disabled.
NIS auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o nis.o nis.cpp
g++ -Wl,-O1 -o nis nis.o   -lnsl 
NIS enabled.
Cups auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o cups.o cups.cpp
cups.cpp:34:23: fatal error: cups/cups.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'cups.o' failed
make: *** [cups.o] Error 1
Cups disabled.
POSIX iconv auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o iconv.o iconv.cpp
g++ -Wl,-O1 -o iconv iconv.o    
POSIX iconv enabled.
Glib auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o glib.o glib.cpp
glib.cpp:36:18: fatal error: glib.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'glib.o' failed
make: *** [glib.o] Error 1
Glib disabled.
ICU auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o icu.o icu.cpp
g++ -Wl,-O1 -o icu icu.o   -licui18n -licuuc -licudata 
ICU enabled.
PulseAudio auto-detection... ()
g++ -c -pipe -O2 -Wall -W -fPIC  -I. -I../../../mkspecs/linux-g++ -o pulseaudio.o pulseaudio.cpp
pulseaudio.cpp:34:30: fatal error: pulse/pulseaudio.h: No such file or directory
compilation terminated.
Makefile:191: recipe for target 'pulseaudio.o' failed
make: *** [pulseaudio.o] Error 1
PulseAudio disabled.
PulseAudio support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to /home/piserver/deps/qt-everywhere-opensource-src-5.4.2/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /home/piserver/deps/qt-everywhere-opensource-src-5.4.2/qtbase/configure to continue.'

**Comment by cryptocx** [comment]
Try to build non static one. The direction just as the one before static build.
When ready to build the qt, issue this command before qmake:
export QTCHOOSER_RUNTOOL=qtconfig
export QT_SELECT=5
Then : 
qmake
make V=s -j4

This -j4, put the number of your cpu core.

**Comment by atze09** [comment]
hello  cryptocx,
Thanks for your reply.
How to build a non static one?
Do i need to copy the static libs manually into the folder?

**Comment by cryptocx** [comment]
Hi atze09,
No, just install all module & dependencies per instruction.

**Comment by atze09** [comment]
i already tried but could not get it running..
i also have problems with
`With UPNP:

    cd src && \
    make -f makefile.unix && \
    strip Lindad

(Recommended) Without UPNP:

    cd src && \
    make -f makefile.unix USE_UPNP= && \
    strip Lindad

To Build Linda-QT
--------

With UPNP:
    qmake -qt=qt5 && \
    make \

(Recommended) Without UPNP:

    qmake -qt=qt5 USE_UPNP=- && \
    make \`

**Comment by cryptocx** [comment]
To build lindad:
>> go to folder where you put linda
cd src
make -f makefile.unix              
strip Lindad

To build qt:
>> go to folder where you put linda
export QTCHOOSER_RUNTOOL=qtconfig
export QT_SELECT=5
qmake                   
make V=s -j4

**Comment by cryptocx** [comment]
Install secp from git:
git clone https://github.com/bitcoin/secp256k1.git
cd secp256k1 
git reset --hard a1d5ae1527240d81ef38af42942db7e4357c9ae4 
./autogen.sh
./configure
make
./tests
sudo make install

**Comment by atze09** [comment]
I could not get it running with above commands.
`piserver@piserver-desktop:~/Linda$ qmake
Project MESSAGE: Building with UPNP support
Project MESSAGE: Building with DBUS (Freedesktop notifications) support
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
piserver@piserver-desktop:~/Linda$ 
`

**Comment by atze09** [comment]
Is there a failure in the tutorial with the folder of the static libs in configure ist is miniQt and in the above it is Qt
`### Compiling QT 5.4.2 statically
Download QT 5.4.2 sources
https://download.qt.io/archive/qt/5.4/5.4.2/single/qt-everywhere-opensource-src-5.4.2.tar.gz<br>
Extract in deps folder
```
tar xvfz qt-everywhere-opensource-src-5.4.2.tar.gz
```
after everything is extracted, create another directory where static libs will be installed. 
For example, i created ~/deps/Qt/5.4.2_static and used that directory in configure command below (it may take a while) :
```
cd ~/deps/qt-everywhere-opensource-src-5.4.2

./configure -static -opensource -release -confirm-license -no-compile-examples -nomake tests -prefix ~/deps/miniQt/5.4.2_static -qt-zlib -qt-libpng -no-libjpeg -qt-xcb -qt-freetype -qt-pcre -qt-harfbuzz -largefile -no-openssl -gtkstyle -skip wayland -skip qtserialport -skip script -pulseaudio -alsa -c++11 -nomake tools
````

**Comment by atze09** [comment]
And here the output of make in the Linda folder.

`piserver@piserver-desktop:~/Linda$ make
cd /home/piserver/Linda/src/leveldb && CC=gcc CXX=g++ make OPT="-pipe -fstack-protector-all --param ssp-buffer-size=1 -DUSE_SECP256K1 -O2" libleveldb.a libmemenv.a
make[1]: Entering directory '/home/piserver/Linda/src/leveldb'
make[1]: 'libleveldb.a' is up to date.
make[1]: 'libmemenv.a' is up to date.
make[1]: Leaving directory '/home/piserver/Linda/src/leveldb'
cd /home/piserver/Linda; /bin/sh share/genbuild.sh /home/piserver/Linda/build/build.h
g++ -c -pipe -fstack-protector-all --param ssp-buffer-size=1 -DUSE_SECP256K1 -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fPIC -DENABLE_WALLET -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DQT_DISABLE_DEPRECATED_BEFORE=0 -DUSE_UPNP=1 -DMINIUPNP_STATICLIB -DSTATICLIB -DUSE_DBUS -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -Isrc -Isrc/json -Isrc/qt -I/home/piserver/deps -Isrc/leveldb/include -Isrc/leveldb/helpers -I/home/piserver/deps/secp256k1/include -I/home/piserver/deps/boost_1_66_0 -I/home/piserver/deps/db-5.0.32.NC/build_unix -I/home/piserver/deps/openssl-1.0.2g/include -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtDBus -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -Ibuild -Ibuild -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o build/wallet.o src/wallet.cpp
src/wallet.cpp: In member function ‘bool CWallet::CreateCoinStake(const CKeyStore&, unsigned int, int64_t, int64_t, CTransaction&, CKey&)’:
src/wallet.cpp:3353:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(pindexBest->nHeight<POS_START_BLOCK)
                           ^
In file included from src/ui_interface.h:9:0,
                 from src/wallet.h:20,
                 from src/wallet.cpp:6:
/home/piserver/deps/boost_1_66_0/boost/signals2/last_value.hpp: In member function ‘boost::signals2::detail::signal2_impl<R, T1, T2, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::detail::signal2_impl<R, T1, T2, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(T1, T2) [with R = bool; T1 = long long int; T2 = const std::__cxx11::basic_string<char>&; Combiner = boost::signals2::last_value<bool>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<bool(long long int, const std::__cxx11::basic_string<char>&)>; ExtendedSlotFunction = boost::function<bool(const boost::signals2::connection&, long long int, const std::__cxx11::basic_string<char>&)>; Mutex = boost::signals2::mutex; boost::signals2::detail::signal2_impl<R, T1, T2, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = bool]’:
/home/piserver/deps/boost_1_66_0/boost/signals2/last_value.hpp:54:36: warning: ‘*((void*)& value +1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if(value) return value.get();
                                    ^
/home/piserver/deps/boost_1_66_0/boost/signals2/last_value.hpp:43:21: note: ‘*((void*)& value +1)’ was declared here
         optional<T> value;
                     ^
g++ -c -pipe -fstack-protector-all --param ssp-buffer-size=1 -DUSE_SECP256K1 -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fPIC -DENABLE_WALLET -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DQT_DISABLE_DEPRECATED_BEFORE=0 -DUSE_UPNP=1 -DMINIUPNP_STATICLIB -DSTATICLIB -DUSE_DBUS -DHAVE_BUILD_INFO -DLINUX -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -Isrc -Isrc/json -Isrc/qt -I/home/piserver/deps -Isrc/leveldb/include -Isrc/leveldb/helpers -I/home/piserver/deps/secp256k1/include -I/home/piserver/deps/boost_1_66_0 -I/home/piserver/deps/db-5.0.32.NC/build_unix -I/home/piserver/deps/openssl-1.0.2g/include -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtDBus -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -Ibuild -Ibuild -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o build/rpcdump.o src/rpcdump.cpp
In file included from /home/piserver/deps/boost_1_66_0/boost/asio/impl/write.hpp:25:0,
                 from /home/piserver/deps/boost_1_66_0/boost/asio/write.hpp:927,
                 from /home/piserver/deps/boost_1_66_0/boost/asio/buffered_write_stream.hpp:29,
                 from /home/piserver/deps/boost_1_66_0/boost/asio/buffered_stream.hpp:22,
                 from /home/piserver/deps/boost_1_66_0/boost/asio.hpp:41,
                 from src/rpcprotocol.h:17,
                 from src/rpcserver.h:10,
                 from src/rpcdump.cpp:9:
/home/piserver/deps/boost_1_66_0/boost/asio/detail/consuming_buffers.hpp: In member function ‘boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepared_buffers_type boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepare(std::size_t)’:
/home/piserver/deps/boost_1_66_0/boost/asio/detail/consuming_buffers.hpp:105:65: error: ‘.’ cannot appear in a constant-expression
     while (next != end && max_size > 0 && result.count < result.max_buffers)
                                                                 ^
/home/piserver/deps/boost_1_66_0/boost/asio/detail/consuming_buffers.hpp:105:50: error: parse error in template argument list
     while (next != end && max_size > 0 && result.count < result.max_buffers)
                                                  ^
Makefile:60274: recipe for target 'build/rpcdump.o' failed
make: *** [build/rpcdump.o] Error 1
`

**Comment by cryptocx** [comment]
Did you put the static dependencies on deps folder?
If you build nonstatic, do not make the deps folder. Let's the compiler find the dependencies from linux.
If you want to build static, i can't help you.

**Comment by atze09** [comment]
I created the deps folder with all the compiled libs.
What is the exact comment for un nonstatic build?
And what do i have to do for an nonstatic build, sorry for my low linux knowledge.

Is the nonstatic something like (without the static command):
./configure  -opensource -release -confirm-license -no-compile-examples -nomake tests -prefix ~/deps/Qt/5.4.2_static -qt-zlib -qt-libpng -no-libjpeg -qt-xcb -qt-freetype -qt-pcre -qt-harfbuzz -largefile -no-openssl -gtkstyle -skip wayland -skip qtserialport -skip script -pulseaudio -alsa -c++11 -nomake tools

**Comment by cryptocx** [comment]
To build non static version, just follow the direction before static version direction. Do not create any deps.

**Comment by atze09** [comment]
I have managed to build non static version.
Thank you very much for your help!!
