### ISSUE TITLE
Version 2.0.0.1 30M MN still not working

### ISSUE THREAD

**Issue by SJablonska** [Lindacoin/Linda#49]
System: Debian 9, latest updates.
Linda version: 2.0.0.1

Tried to setup 30M MN using current MN and did a cold setup.

Both do not work. Both show same errors:

From the debug log:
GUI: QXcbConnection: XCB error: 148 (Unknown), sequence: 165, resource id: 0, major code: 140 (Unknown), minor code: 20
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: QCoreApplication::postEvent: Unexpected null receiver
Error: while parsing masternode.conf Error:
.
.
2018-04-11 11:45:09 CActiveMasternode::GetMasterNodeVin - Could not locate specified vin from possible list
2018-04-11 11:45:09 CActiveMasternode::ManageStatus() - Could not find suitable coins!
2018-04-11 11:45:09 CActiveMasternode::Dseep() - Error: masternode is not in a running status
2018-04-11 11:45:09 CActiveMasternode::ManageStatus() - Error on Ping: masternode is not in a running statusAttempting to lock wallet
So, it is not running. I know I could set up a new wallet, etc. but it would be nice if my MN would just start

From the console:
masternode start
not capable masternode(cmd=start): Unknown. Check debug.log for more information.

**Comment by davidstoneham** [comment]
are you able to setup a masternode with exactly 2 million coins instead of 30 million?

**Comment by SJablonska** [comment]
Nope, because team stated new wallet version would fix 30M MN.

**Comment by davidstoneham** [comment]
I was just looking at the code and it looks like it might only allow 2 million coin master nodes.
I've also just looked through the commits for version 2.0.0.1 and there isn't anything referencing a fix for 30million coin masternodes

**Comment by SJablonska** [comment]
Hard to believe, because that would mean that every 30M MN holder has to change their wallet(s).

Anyway, thanks for your help!

**Comment by SJablonska** [comment]
2M works

**Comment by AnabolicRampage** [comment]
30 million MN's will no longer work

**Comment by davidstoneham** [comment]
@AnabolicRampage just a heads up. The network has been changed to 2M masternode. This means exactly 2M coins are required to be a masternode. It's not possible to have different numbers of coins for masternode as they would not gain network consensus as transactions would be signed in different formats which would result in a fork being created. So you'll have to stick with just 2M masternodes :)

**Comment by Marcin0011** [comment]
@SJablonska  czy jesteś w stanie udzielić mi pomocy z uruchomieniem MN lindy?

**Comment by davidstoneham** [comment]
@Marcin0011 przewodnik konfiguracji dla mn można znaleźć na tej stronie  http://lindaprojectinfo.com

**Comment by RegencySoftware** [comment]
I am seeing this same issue on a 2M Master node. I have one, this is my second and I cannot get it to run.

CActiveMasternode::ManageStatus() - Checking inbound connection to 'xx.xx.xx.xx:33820'
CActiveMasternode::GetMasterNodeVin - Could not locate specified vin from possible list
CActiveMasternode::ManageStatus() - Could not find suitable coins!
CActiveMasternode::Dseep() - Error: masternode is not in a running status
CActiveMasternode::ManageStatus() - Error on Ping: masternode is not in a running statusAttempting to lock wallet connected to self at xx.xx.xx.xx:53030, disconnecting

**Comment by davidstoneham** [comment]
@RegencySoftware this error means that the wallet can't find the transaction for exactly 2million coins on the address.

**Things to check:**
- Make you're you've sent a single transaction with exactly 2million coins to the address and it has 15 confirmations (you can look up the address on https://prohashing.com/explorer/Lindacoin/)
- Have you specified the correct vin index (there is a command in the wallet to list the vin transaction ids and index for your masternode address)
- Is your config setup with the correct txid and masternode wallet address

Also on a side note, you can only run 1 masternode per ip address.

**Comment by BraapAround** [comment]
Please close this issue.
