### ISSUE TITLE
Wallet stuck in stake

### ISSUE THREAD

**Issue by amn357** [Lindacoin/Linda#51]
repair wallet no issue will not sync. stuck in stake

**Comment by Chris-Lindacoin** [comment]
Hey @amn357 did yo sort this out?  give me a shout if you still need help chris@lindacoin.com

**Comment by amn357** [comment]
Solved Thanks!!

*Angel Neris SL#3293576*
*Living Realty llc *
*1444 Biscayne Blvd #314*
*Miami, FL 33132*

**Comment by BraapAround** [comment]
@amn357 Please close this issue.
